languageCode = "zh-tw"
languageName ="Chinese"
weight = 1
title = "兔姬百科"

[params]
  displayName = "TW"
  isoCode = "tw"
  rtl = false
  dateFormat = "29 June 2023"
  logo = "img/logo.png"
  # secondaryLogo = "PATH"
  description = "廣大姬友共同完成的歷史大業"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "兔姬百科"
  image = "img/logo.png"
  headline = "兔姬百科2.0 歡迎各路姬友前來編輯"
  bio = ""
  links = [
    { twitter = "https://twitter.com/kuroxusagihime" },
    { youtube = "https://www.youtube.com/channel/UC0u_-3zgLkSYpQOxlBi-5Ng" },
    { discord = "https://discord.com/invite/k2wKjtKW2v" },
    { link = "https://usagihime.net" },
  ]